from django.urls import path

from frontend.views import (
    ConsultantsView,
    CorporateGovernaceView,
    EngineeringView,
    FunctionsView,
    HistoryView,
    HomeView,
    ManagementView,
    ManagingDirectorView,
    MandateView,
    MissionVisionView,
    PeopleView,
    PracticeView,
    PrincipalConsultantsView,
    PrinciplesView,
    ProjectDetailView,
    ProjectView,
    SectorMinistryView,
    SeniorConsultantsView,
    ServiceView,
    StaffDetailView,
)

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("projects/", ProjectView.as_view(), name="projects"),
    path("project/<int:pk>/", ProjectDetailView.as_view(), name="project_detail"),
    path("practice/", PracticeView.as_view(), name="practice"),
    path(
        "practice/sector-ministry/",
        SectorMinistryView.as_view(),
        name="sector_ministry",
    ),
    path(
        "practice/corporate-governance/",
        CorporateGovernaceView.as_view(),
        name="corporate_governance",
    ),
    path(
        "practice/management/",
        ManagementView.as_view(),
        name="management",
    ),
    path(
        "practice/management/<int:pk>/", StaffDetailView.as_view(), name="staff_detail"
    ),
    path(
        "practice/management/managing-director/",
        ManagingDirectorView.as_view(),
        name="managing_director",
    ),
    path(
        "practice/management/deputy-managing-director/engineering/",
        EngineeringView.as_view(),
        name="engineering",
    ),
    path(
        "practice/history/",
        HistoryView.as_view(),
        name="history",
    ),
    path(
        "practice/functions/",
        FunctionsView.as_view(),
        name="functions",
    ),
    path(
        "practice/mandate/",
        MandateView.as_view(),
        name="mandate",
    ),
    path(
        "practice/mission-vision-and-values/",
        MissionVisionView.as_view(),
        name="mission_vision",
    ),
    path(
        "practice/services/",
        ServiceView.as_view(),
        name="services",
    ),
    path(
        "principles/",
        PrinciplesView.as_view(),
        name="principles",
    ),
    path(
        "people/",
        PeopleView.as_view(),
        name="people",
    ),
    path(
        "consultants/principal-consultants/",
        PrincipalConsultantsView.as_view(),
        name="principal_consultants",
    ),
    path(
        "consultants/senior-consultants/",
        SeniorConsultantsView.as_view(),
        name="senior_consultants",
    ),
    path(
        "consultants/consultants/",
        ConsultantsView.as_view(),
        name="consultants",
    ),
]
