# Generated by Django 6.0 on 2025-12-18 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('client', models.CharField(max_length=200)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='projects/main_pictures/')),
                ('little_text_details', models.TextField()),
                ('project_coordinator', models.CharField(max_length=150)),
                ('total_floor_area', models.CharField(help_text='e.g. 5,000 sqm', max_length=100)),
                ('start_date', models.DateField()),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('job_sheets', models.TextField(blank=True, help_text='Job sheet description')),
                ('certificate', models.TextField(blank=True, help_text='Certification details')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='frontend.projectcategory')),
                ('project_leaders', models.ManyToManyField(related_name='projects', to='frontend.projectleader')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/gallery/')),
                ('image_type', models.CharField(choices=[('project', 'Project Pictures'), ('construction', 'Construction Pictures')], max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='frontend.project')),
            ],
        ),
    ]
