# Generated by Django 6.0 on 2025-12-18 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='location',
            field=models.TextField(default='Accra', help_text='Project location'),
        ),
        migrations.AlterField(
            model_name='project',
            name='certificate',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='job_sheets',
            field=models.TextField(blank=True),
        ),
    ]
