# Generated by Django 6.0 on 2025-12-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_project_location_alter_project_certificate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='certificate',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='project',
            name='job_sheets',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='project',
            name='location',
            field=models.CharField(default='Accra', max_length=300),
        ),
    ]
