# Generated by Django 6.0 on 2025-12-19 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_alter_project_certificate_alter_project_job_sheets_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('award_name', models.CharField(max_length=200)),
                ('awarded_by', models.CharField(max_length=200)),
                ('website', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='frontend.project')),
            ],
            options={
                'ordering': ['-year', 'award_name'],
            },
        ),
    ]
