# Generated by Django 6.0 on 2025-12-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_projectaward'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='other_team_members',
            field=models.ManyToManyField(blank=True, related_name='projects', to='frontend.projectteammember'),
        ),
    ]
