# Generated by Django 6.0 on 2025-12-20 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_projectteammember_project_other_team_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractorRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Contractor Role',
                'verbose_name_plural': 'Contractor Roles',
            },
        ),
        migrations.CreateModel(
            name='ProjectContractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractors', to='frontend.project')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_contractors', to='frontend.contractorrole')),
            ],
            options={
                'ordering': ('role__name',),
                'unique_together': {('project', 'role')},
            },
        ),
    ]
