# Generated by Django 6.0 on 2025-12-27 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_maincategory_subcategory_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='region',
            field=models.CharField(blank=True, default='Not a Regional Head', max_length=100),
        ),
    ]
