# Generated by Django 6.0 on 2026-01-01 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_person_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('download', models.FileField(blank=True, null=True, upload_to='publications/')),
            ],
        ),
    ]
