# Generated by Django 6.0 on 2026-01-16 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0011_publications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='image_type',
            field=models.CharField(choices=[('project', 'Project Pictures'), ('construction', 'Construction Pictures'), ('project_3d_visualizations', 'Project 3D Visualizations')], max_length=30),
        ),
    ]
