# Generated by Django 6.0 on 2026-01-20 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0013_boardmember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardmember',
            name='image',
        ),
        migrations.AddField(
            model_name='boardmember',
            name='position',
            field=models.CharField(default='Board Member', max_length=255),
        ),
    ]
