# Generated by Django 6.0 on 2026-01-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0014_remove_boardmember_image_boardmember_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardmember',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='board_members/'),
        ),
    ]
