# Generated by Django 6.0 on 2026-01-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0015_boardmember_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='total_floor_area',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='staff',
            name='region',
            field=models.CharField(default='Not a Regional Head', max_length=100),
        ),
    ]
