# Generated by Django 6.0 on 2026-01-22 13:39

import frontend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0016_alter_project_total_floor_area_alter_staff_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='people/')),
                ('profession', models.CharField(max_length=255)),
                ('department', models.CharField(default='tech', max_length=255)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            bases=(models.Model, frontend.models.ImageOptimizeMixin),
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
