# Generated by Django 6.0 on 2026-02-03 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0017_people_delete_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='publications',
            name='publication_image',
            field=models.ImageField(blank=True, null=True, upload_to='publications/images/'),
        ),
    ]
