# Generated by Django 6.0 on 2026-02-04 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0018_publications_publication_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload the main image for the gallery', upload_to='projects-gallery/', verbose_name='Gallery Image')),
                ('category', models.CharField(blank=True, db_index=True, help_text='e.g. Traditional Dance, Community Event, Art Exhibition, etc.', max_length=100, verbose_name='Category')),
                ('alt_text', models.CharField(blank=True, help_text='Descriptive text for accessibility and SEO (screen readers)', max_length=255, verbose_name='Image Alt Text')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Upload Date')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this image without deleting it', verbose_name='Visible')),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['category'], name='frontend_ga_categor_4bcfe4_idx')],
            },
        ),
    ]
