# Generated by Django 6.0 on 2026-02-04 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0019_galleryimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GalleryImage',
            new_name='ProjectGalleryImage',
        ),
        migrations.RenameIndex(
            model_name='projectgalleryimage',
            new_name='frontend_pr_categor_a35524_idx',
            old_name='frontend_ga_categor_4bcfe4_idx',
        ),
    ]
