# Generated by Django 6.0 on 2026-02-04 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0020_rename_galleryimage_projectgalleryimage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectgalleryimage',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Project Gallery Image', 'verbose_name_plural': 'Project Gallery Images'},
        ),
        migrations.AlterField(
            model_name='projectgalleryimage',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Descriptive text for accessibility and SEO (screen readers)', max_length=500, verbose_name='Image Alt Text'),
        ),
        migrations.AlterField(
            model_name='projectgalleryimage',
            name='category',
            field=models.CharField(blank=True, db_index=True, help_text='e.g. Education, Sport and Leisure, Culture, etc.', max_length=100, verbose_name='Category'),
        ),
    ]
