# Generated by Django 6.0 on 2026-02-04 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0021_alter_projectgalleryimage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectgalleryimage',
            name='image',
            field=models.ImageField(help_text='Upload the main image for the gallery', max_length=350, upload_to='projects-gallery/', verbose_name='Gallery Image'),
        ),
    ]
