# Generated by Django 6.0 on 2026-02-04 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0022_alter_projectgalleryimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectgalleryimage',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Descriptive text for accessibility and SEO (screen readers)', max_length=500, unique=True, verbose_name='Image Alt Text'),
        ),
    ]
