# Generated by Django 6.0 on 2026-02-05 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0023_alter_projectgalleryimage_alt_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardmember',
            options={'ordering': ['-joined_at', 'name'], 'verbose_name': 'Board Member', 'verbose_name_plural': 'Board Members'},
        ),
        migrations.RemoveField(
            model_name='boardmember',
            name='created_at',
        ),
        migrations.AddField(
            model_name='boardmember',
            name='joined_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Date this board member joined (used for ordering)', null=True, verbose_name='Joined Date'),
        ),
    ]
