# Generated by Django 6.0 on 2026-02-11 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0024_alter_boardmember_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='grade',
            new_name='position',
        ),
        migrations.AddField(
            model_name='staff',
            name='profession',
            field=models.CharField(default='Surveying', max_length=100),
        ),
    ]
