# Generated by Django 6.0 on 2026-02-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0025_rename_grade_staff_position_staff_profession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='department',
        ),
        migrations.RemoveField(
            model_name='people',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='people',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='people',
            name='twitter',
        ),
        migrations.AddField(
            model_name='people',
            name='position',
            field=models.CharField(default='position', max_length=100),
        ),
        migrations.AddField(
            model_name='people',
            name='region',
            field=models.CharField(default='Region', max_length=100),
        ),
        migrations.AlterField(
            model_name='people',
            name='profession',
            field=models.CharField(default='Surveying', max_length=100),
        ),
    ]
