# Generated by Django 6.0 on 2026-02-11 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0026_remove_people_department_remove_people_facebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='category',
            field=models.CharField(default='category', max_length=100),
        ),
    ]
