# Generated by Django 6.0 on 2026-02-11 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0027_people_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='department',
            field=models.CharField(default='c', max_length=100),
        ),
    ]
