# Generated by Django 6.0 on 2026-02-11 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0028_people_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='people',
            name='position',
            field=models.CharField(blank=True, default='position', max_length=100),
        ),
        migrations.AlterField(
            model_name='people',
            name='region',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
