# Generated by Django 6.0 on 2026-02-14 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0031_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='latitude',
            field=models.FloatField(blank=True, help_text='e.g., 5.6037 for Accra', null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='longitude',
            field=models.FloatField(blank=True, help_text='e.g., -0.1870 for Accra', null=True),
        ),
    ]
