# Generated by Django 6.0 on 2026-02-18 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0032_alter_branch_latitude_alter_branch_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, help_text='Auto-generated from title for clean URLs', max_length=250),
        ),
        migrations.AddField(
            model_name='projectgalleryimage',
            name='image_type',
            field=models.CharField(blank=True, default='Main', help_text='main project image', max_length=30, verbose_name='Image Type'),
        ),
        migrations.AddField(
            model_name='projectgalleryimage',
            name='image_type_link',
            field=models.URLField(blank=True, help_text='Link to the image type', max_length=350, verbose_name='Image Type Link'),
        ),
        migrations.AddField(
            model_name='projectgalleryimage',
            name='related_project',
            field=models.ForeignKey(blank=True, help_text='If this image belongs to one of your projects, link it here. Clicking the image will go to that project page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_gallery_images', to='frontend.project', verbose_name='Linked Project (optional)'),
        ),
    ]
