# Generated by Django 6.0 on 2026-02-18 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0033_project_slug_projectgalleryimage_image_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='picture',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='projects/main_pictures/'),
        ),
    ]
