# Generated by Django 6.0 on 2026-02-18 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0034_alter_project_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectgalleryimage',
            name='image_type',
        ),
        migrations.RemoveField(
            model_name='projectgalleryimage',
            name='image_type_link',
        ),
    ]
