# Generated by Django 6.0 on 2026-02-18 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0035_remove_projectgalleryimage_image_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectgalleryimage',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Descriptive text for accessibility and SEO (screen readers)', max_length=500, verbose_name='Image Alt Text'),
        ),
    ]
