# Generated by Django 6.0 on 2026-02-18 21:18

import frontend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0036_alter_projectgalleryimage_alt_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(default='default.jpg', upload_to='board_members/')),
                ('about', models.TextField()),
                ('joined_at', models.DateTimeField(blank=True, db_index=True, help_text='Date this board member joined (used for ordering)', null=True, verbose_name='Joined Date')),
            ],
            options={
                'verbose_name': 'Alumni',
                'verbose_name_plural': 'Alumnis',
                'ordering': ['-joined_at', 'name'],
            },
            bases=(models.Model, frontend.models.ImageOptimizeMixin),
        ),
    ]
