# Generated by Django 6.0 on 2026-02-19 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0037_alumni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmember',
            name='image',
            field=models.ImageField(default='default.jpg', max_length=300, upload_to='board_members/'),
        ),
    ]
