# Generated by Django 6.0 on 2026-02-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0038_alter_boardmember_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumni',
            options={'ordering': ['-joined_at', 'name'], 'verbose_name': 'Alumni', 'verbose_name_plural': 'Alumni'},
        ),
        migrations.AddField(
            model_name='alumni',
            name='Project_image',
            field=models.ImageField(blank=True, null=True, upload_to='alumni_projects/', verbose_name='Project Image'),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='board_members/', verbose_name='Profile Photo'),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='joined_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Date this alumni joined (used for ordering)', null=True, verbose_name='Joined Date'),
        ),
    ]
