# Generated by Django 6.0 on 2026-02-19 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0039_alter_alumni_options_alumni_project_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumni',
            old_name='Project_image',
            new_name='project_image',
        ),
    ]
