# Generated by Django 6.0 on 2026-02-19 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0040_rename_project_image_alumni_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='project_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Project Name'),
        ),
    ]
