# Generated by Django 6.0 on 2026-02-19 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0041_alumni_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='project_image',
            field=models.ImageField(blank=True, max_length=300, null=True, upload_to='alumni_projects/', verbose_name='Project Image'),
        ),
    ]
