# Generated by Django 6.0 on 2026-02-19 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0042_alter_alumni_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='image',
            field=models.ImageField(default='default.jpg', max_length=300, upload_to='board_members/', verbose_name='Profile Photo'),
        ),
    ]
