# Generated by Django 6.0 on 2026-02-19 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0043_alter_alumni_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='telephone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
