# Generated by Django 6.0 on 2026-06-28 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0044_branch_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='latitude',
            field=models.FloatField(blank=True, help_text='e.g., 5.6037 for Accra', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='longitude',
            field=models.FloatField(blank=True, help_text='e.g., -0.1870 for Accra', null=True),
        ),
    ]
