# Generated by Django 6.0 on 2026-06-30 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0046_alter_project_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(blank=True, help_text='e.g., 5.6037 for Accra', null=True)),
                ('longitude', models.FloatField(blank=True, help_text='e.g., -0.1870 for Accra', null=True)),
            ],
            options={
                'verbose_name_plural': 'ProjectLocation',
            },
        ),
    ]
