# Generated by Django 6.0 on 2026-06-30 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0048_alter_projectlocation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectlocation',
            name='region',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
