# Generated by Django 6.0 on 2026-07-09 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0049_projectlocation_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='rank',
            field=models.CharField(blank=True, default='rank', max_length=100),
        ),
    ]
