# Generated by Django 6.0 on 2026-07-13 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0050_people_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='category',
        ),
        migrations.AlterField(
            model_name='people',
            name='rank',
            field=models.CharField(default='category', max_length=100),
        ),
    ]
