# Generated by Django 6.0 on 2026-07-22 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0052_alter_newsarticle_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='source_url',
            field=models.URLField(blank=True, help_text='Original source link for external news articles', max_length=500, null=True),
        ),
    ]
